name: starter_project
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bot_toast: ^4.0.3
  
  cupertino_icons: ^1.0.2

  chopper: ^4.0.5

  equatable: ^2.0.5

  flutter_bloc: ^8.1.1

  flutter_dialogs: ^3.0.0

  flutter_screenutil: ^5.6.0

  flutter_svg: ^1.1.6

  http: ^0.13.5

  json_annotation: 4.7.0

  logging: ^1.1.1

  shared_preferences: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.0.3

  chopper_generator: ^4.0.5
  
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

